### ISSUE TITLE
E-Mails not sent if "Enable large site" is disabled

### ISSUE THREAD

**Issue by msom** [collective/collective.logbook#1]
We have a Plone 4.1.6 site with collective.logbook 0.7 installed and E-Mails are only sent when the "Enable large site" option is enabled.

**Comment by idgserpro** [comment]
Same here, Plone 4.3.9 and collective.logbook 0.7.

**Comment by ramonski** [comment]
Should be fixed in the current `master` branch, which will be version `0.8` when released.
