### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by rafaelbco** [collective/collective.logbook#14]
May we have a release? I fixed #12 (Error while trying to login into the ZMI) a while ago and the add-on seems to be working ok since then.

**Comment by ramonski** [comment]
Thanks @rafaelbco, I'll do a release soon.

I wanted to add a migration step for versions coming from logbook 0.6 (see #11), could you maybe help with some coding here?

**Comment by rafaelbco** [comment]
I'm on it :smile:

**Comment by ramonski** [comment]
Thanks mate, much appreciated!
I can support you with reviewing your PR if you like...
@msom: stay tuned, you'll be the first who will test;)

**Comment by ramonski** [comment]
Released Version 0.9.0:
https://pypi.python.org/pypi/collective.logbook/0.9.0
Thanks @rafaelbco!
