### ISSUE TITLE
please add pypi classifiers

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.logbook#5]
...to indicate Plone 5 support and maybe update the README to indicate Plone 5 support - thanks!

"Framework :: Plone :: 5.0", 
"Framework :: Plone :: 5.1",

**Comment by ramonski** [comment]
Thanks for the hint, I will add it in the next version, which looks like it is coming soon.

**Comment by tkimnguyen** [comment]
I just added the one for 5.0 since I haven't actually tested it with 5.1...
